#!name=爱企查

#!desc=爱企查vip

#!homepage=https://www.github.com/fiywind

#!author=fiywind

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/aqc.png


^https?:\/\/m\.aiqicha\.baidu\.com\/user\/getuserinfo url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/aqc.js
^https?:\/\/m\.aiqicha\.baidu\.com\/vip\/getviptips url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/aqc.js

hostname = m.aiqicha.baidu.com
