#!name=彩云天气SVIP

#!desc=彩云天气会员解锁

#!author=fiywind

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/caiyun.png


^https?:\/\/biz\.cyapi\.cn\/v\d\/user url script-echo-response https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/caiyun_svip.js

hostname = biz.cyapi.cn, *.cyapi.cn, buy.itunes.apple.com
