#!name=彩云天气SVIP

#!desc=彩云天气会员解锁

#!author=fiywind

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/caiyun.png



hostname=*.caiyunapp.*,*cyapi*,biz.cyapi.cn,buy.itunes.apple.com

^https?:\/\/biz\.cyapi\.cn\/v\d\/user url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/caiyun_svip.js

^https:\/\/ad\.caiyunapp\.com\/ url reject
