#!name=分贝仪专业版 DB Meter Pro
#!desc=分贝仪专业版解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/alarmy.png
#!homepage=https://yfamilys.com
#!author=fiywind


^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$ url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/dbmeter_pro.js

hostname = buy.itunes.apple.com
