#!name=icost

#!desc=icost解锁永久vip

#!homepage=https://www.github.com/fiywind

#!author=fiywind

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/aqc.png


^https?:\/\/.*\.icostapp\.com\/.* url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/icost.js


hostname = buy.itunes.apple.com, *.icostapp.com
