#!name=Notability_Plus
#!desc=Notability解锁订阅
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/notability.png
#!homepage=https://github.com/fiywind
#!author=fiywind
#!date=2026-04-09



# Notability 解锁 (指向你的 GitHub 链接)
^https?:\/\/notability\.com\/api\/v1\/subscriptions url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/notability_plus.js

hostname = notability.com
