#!name=Safari漏洞封堵&病毒防范脚本
#!desc=safarihardened
#!author=fiywind
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/adguard.png

# 1. 专门针对 html5test 主页的规则 (优先级最高)
^https?:\/\/html5test\.com\/($|\?|index\.html) url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/safarihardened.js

# 2. 通用网页匹配：排除 API、JSON 以及微信/苹果内部域名
# 逻辑：匹配 .com/.cn 等后缀，但排除掉包含 'weixin', 'apple', 'short', 'api' 的路径
^https?:\/\/(?!(.*(weixin|apple|api|short|google|cloud))).*(\.com|\.cn|\.net|\.org|\.cc) url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/safarihardened.js

hostname = *.com, *.net, *.org, *.xyz, *.me, *.online, *.top, *.cc, html5test.com
