#!name=Safari漏洞封堵&病毒防范脚本
#!desc=safarihardened
#!author=fiywind
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/adguard.png

# 仅当流量来自 Safari 时，才执行网页加固脚本
^https?:\/\/.* url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/safarihardened.js

hostname = *.com, *.cn, *.net, *.org, *.xyz, *.me, *.online, *.top, *.cc, html5test.com, bhip.cc.cd
