#!name=Widgy
#!desc=Widgy全功能解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/alarmy.png
#!homepage=https://github.com/fiywind
#!author=fiywind


^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$ url script-response-body https://raw.githubusercontent.com/fiywind/spuer_scripts/refs/heads/main/widgy_unlock.js

hostname = buy.itunes.apple.com
